# Generated by Django 5.2 on 2025-04-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_appuser_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
